# Generated by Django 2.2.8 on 2019-12-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=55, null=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=63, verbose_name='Email')),
                ('password', models.CharField(max_length=63, verbose_name='Password')),
                ('address1', models.CharField(max_length=255, verbose_name='Address1')),
                ('address2', models.CharField(max_length=255, verbose_name='Address2')),
                ('city', models.CharField(max_length=63, verbose_name='City')),
                ('zip', models.CharField(max_length=20, verbose_name='Zip code')),
                ('check', models.BooleanField(default=False, verbose_name='Check')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='validate_app.State')),
            ],
        ),
    ]
