# Generated by Django 2.2.8 on 2019-12-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodel',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address1'),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address2'),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Check'),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='city',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='username',
            field=models.CharField(max_length=55, verbose_name='Username'),
        ),
    ]
