# Generated by Django 2.2.8 on 2019-12-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validate_app', '0002_auto_20191224_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodel',
            name='state',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='validate_app.State'),
        ),
    ]
